// adicione aqui os seus produtos fixos:

var itemsByCategory = {
    'polpas': [
        { discr: 'Polpa de abacaxi', pUnit: '', medida: ''},
        { discr: 'Polpa de abacaxi com hortelã', pUnit: '', medida: ''},
        { discr: 'Polpa de caju', pUnit: '', medida: ''},
        { discr: 'Polpa de acerola', pUnit: '', medida: ''},
        { discr: 'Polpa de maracujá', pUnit: '', medida: ''},
        { discr: 'Polpa de morango', pUnit: '', medida: ''},
        { discr: 'Polpa de cupuaçu', pUnit: '', medida: ''},
        { discr: 'Polpa de graviola', pUnit: '', medida: ''},
        { discr: 'Polpa de umbu verde', pUnit: '', medida: ''},
        { discr: 'Polpa de uva', pUnit: '', medida: ''},
        { discr: 'Polpa de goiaba', pUnit: '', medida: ''},
        { discr: 'Polpa de manga', pUnit: '', medida: ''},
        { discr: 'Polpa de açaí', pUnit: '', medida: ''},
        { discr: 'Polpa de limão', pUnit: '', medida: ''},
        { discr: 'Polpa de tangerina', pUnit: '', medida: ''},
        { discr: 'Polpa de ameixa', pUnit: '', medida: ''}
    ],
    'congelados': [
        { discr: 'Amora congelada', pUnit: '', medida: ''},
        { discr: 'Frutas vermelhas congelada', pUnit: '', medida: ''},
        { discr: 'Framboesa', pUnit: '', medida: ''},
        { discr: 'Mirtilo', pUnit: '', medida: ''},
        { discr: 'Morango congelado', pUnit: '', medida: ''}
    ],
    'temperos': [
        { discr: 'Chimichurri', pUnit: '7.00', medida: 'unid'},
        { discr: 'Ana Maria', pUnit: '7.00', medida: 'unid'},
        { discr: 'Edu Guedes', pUnit: '7.00', medida: 'unid'},
        { discr: 'Tempero Mineiro', pUnit: '7.00', medida: 'unid'},
        { discr: 'Açafrão', pUnit: '7.00', medida: 'unid'},
        { discr: 'Vinagre em pó', pUnit: '7.00', medida: 'unid'},
        { discr: 'Tártaro', pUnit: '7.00', medida: 'unid'},
        { discr: 'Pega marido', pUnit: '7.00', medida: 'unid'},
        { discr: 'Agarra marido', pUnit: '7.00', medida: 'unid'},
        { discr: 'Colorau puro', pUnit: '7.00', medida: 'unid'},
        { discr: 'Cominho puro', pUnit: '7.00', medida: 'unid'},
        { discr: 'Cominho com pimenta', pUnit: '7.00', medida: 'unid'},
        { discr: 'Dry rub', pUnit: '7.00', medida: 'unid'},
        { discr: 'Cebola e alho', pUnit: '7.00', medida: 'unid'},
        { discr: 'Cebola, alho e salsa', pUnit: '7.00', medida: 'unid'},
        { discr: 'Cebola em pó', pUnit: '7.00', medida: 'unid'},
        { discr: 'Alho desidratado', pUnit: '7.00', medida: 'unid'},
        { discr: 'Lascas de alho', pUnit: '7.00', medida: 'unid'},
        { discr: 'Curry', pUnit: '7.00', medida: 'unid'},
        { discr: 'Lemon e Ervas finas', pUnit: '7.00', medida: 'unid'},
        { discr: 'Tempero gaúcho', pUnit: '7.00', medida: 'unid'},
        { discr: 'Tempero para arroz', pUnit: '7.00', medida: 'unid'},
        { discr: 'Tempero para feijão', pUnit: '7.00', medida: 'unid'},
        { discr: 'Páprica defumada', pUnit: '7.00', medida: 'unid'},
        { discr: 'Páprica doce', pUnit: '7.00', medida: 'unid'},
        { discr: 'Lemon Pepper', pUnit: '7.00', medida: 'unid'},
        { discr: 'Tomate seco', pUnit: '7.00', medida: 'unid'},
        { discr: 'Sal defumado', pUnit: '7.00', medida: 'unid'},
        { discr: 'Sal rosa do Himalaia', pUnit: '7.00', medida: 'unid'},
        { discr: 'Sal de Ervas', pUnit: '7.00', medida: 'unid'},
        { discr: 'Sal parrilha p/churrasco', pUnit: '7.00', medida: 'unid'},
        { discr: 'Bicarbonato de sódio', pUnit: '7.00', medida: 'unid'},
        { discr: 'Bacon desidratado vegano', pUnit: '7.00', medida: 'unid'},
        { discr: 'Coentro muido', pUnit: '7.00', medida: 'unid'},
        { discr: 'Grão de coentro', pUnit: '7.00', medida: 'unid'},
        { discr: 'Salsa', pUnit: '7.00', medida: 'unid'},
        { discr: 'Orégano', pUnit: '7.00', medida: 'unid'},
        { discr: 'Pimenta calabresa', pUnit: '7.00', medida: 'unid'},
        { discr: 'Gengibre em pó', pUnit: '7.00', medida: 'unid'},
        { discr: 'Tempero fit natural', pUnit: '7.00', medida: 'unid'},
        { discr: 'Tempero fit completo', pUnit: '7.00', medida: 'unid'},
        { discr: 'Tempero fit para carne', pUnit: '7.00', medida: 'unid'},
        { discr: 'Tempero fit para frango', pUnit: '7.00', medida: 'unid'}
    ],
    'farinhas': [
        { discr: 'Farinha de beringela', pUnit: '', medida: ''},
        { discr: 'Farinha de batata doce', pUnit: '', medida: ''},
        { discr: 'Farinha de banana verde', pUnit: '', medida: ''},
        { discr: 'Farinha de maracujá', pUnit: '', medida: ''},
        { discr: 'Farinha de linhaça marrom', pUnit: '', medida: ''},
        { discr: 'Farinha de linhaça dourada', pUnit: '', medida: ''},
        { discr: 'Farinha multimistura completo', pUnit: '', medida: ''},
        { discr: 'Farinha de arroz', pUnit: '', medida: ''},
        { discr: 'Pó de guaraná', pUnit: '', medida: ''},
        { discr: 'Cacau em pó', pUnit: '', medida: ''},
        { discr: 'Colágeno', pUnit: '', medida: ''}
    ],
    'oleaginosas': [
        { discr: 'Mix de amendoins 300g', pUnit: '', medida: 'unid'},
        { discr: 'Castanha de caju 160g', pUnit: '', medida: 'unid'},
        { discr: 'Castanha de caju caramelizada 150g', pUnit: '', medida: 'unid'},
        { discr: 'Castanha do Pará 100g', pUnit: '', medida: 'unid'},
        { discr: 'Nozes 100g', pUnit: '', medida: 'unid'},
        { discr: 'Semente de chia', pUnit: '', medida: 'unid'},
        { discr: 'Semente de linhaça dourada', pUnit: '', medida: 'unid'},
        { discr: 'Somente de linhaça marrom', pUnit: '', medida: 'unid'},
        { discr: 'Semente de girassol', pUnit: '', medida: 'unid'},
        { discr: 'Semente de jerimum', pUnit: '', medida: 'unid'},
        { discr: 'Aveia em flocos', pUnit: '', medida: 'unid'},
        { discr: 'Granola gourmet 450g', pUnit: '', medida: 'unid'},
        { discr: 'Granola 250g', pUnit: '', medida: 'unid'},
        { discr: 'Grão de bico', pUnit: '', medida: 'unid'},
        { discr: 'Mix de grãos', pUnit: '', medida: 'unid'},
        { discr: '7 grãos (quinoa, linhaça, girassol, abóbora, amaranto, gergelim, chia)', pUnit:'', medida: 'unid'},
        { discr: 'Tâmara', pUnit: '', medida: 'unid'},
        { discr: 'Cogumelo shitake', pUnit: '', medida: 'unid'},
        { discr: 'Vinagre de maçã 500ml', pUnit: '9.00', medida: 'unid'}
    ],
    'embandejados': [
        { discr: 'Pimenta de cheiro 200g', pUnit: '2.00', medida: 'unid'},
        { discr: 'Jiló 200g', pUnit: '2.00', medida: 'unid'},
        { discr: 'Vagem 200g', pUnit: '2.00', medida: 'unid'},
        { discr: 'Vagem portuguesa 200g', pUnit: '2.00', medida: 'unid'},
        { discr: 'Quiabo 200g', pUnit: '2.00', medida: 'unid'},
        { discr: 'Maxixe 200g', pUnit: '2.00', medida: 'unid'}
    ],
    'mel': [
        { discr: 'Mel garrafa 1l', pUnit: '35.00', medida: 'unid'},
        { discr: 'Mel garrafa 300ml', pUnit: '13.00', medida: 'unid'},
        { discr: 'Favos de Mel 200ml', pUnit: '10.00', medida: 'pote'}
    ],
    'hortaliças': [
        { discr: 'Alface crespa', pUnit: '2.00', medida: 'unid'},
        { discr: 'Alface americana', pUnit: '2.00', medida: 'unid'},
        { discr: 'Alface roxa', pUnit: '2.00', medida: 'unid'},
        { discr: 'Alface lisa', pUnit: '2.00', medida: 'unid'},
        { discr: 'Coentro', pUnit: '3.00', medida: 'unid'},
        { discr: 'Cebolinha', pUnit: '2.00', medida: 'unid'},
        { discr: 'Alho poró', pUnit: '2.50', medida: 'unid'},
        { discr: 'Salsinha', pUnit: '2.00', medida: 'unid'},
        { discr: 'Salsão', pUnit: '2.00', medida: 'unid'},
        { discr: 'Hortelã', pUnit: '2.00', medida: 'unid'},
        { discr: 'Alecrim', pUnit: '2.00', medida: 'unid'},
        { discr: 'Manjericão', pUnit: '2.00', medida: 'unid'},
        { discr: 'Rúcula', pUnit: '2.00', medida: 'unid'},
        { discr: 'Couve', pUnit: '2.00', medida: 'unid'},
        { discr: 'Espinafre', pUnit: '2.00', medida: 'unid'},
        { discr: 'Agrião', pUnit: '2.00', medida: 'unid'}
    ],
    'frutas': [
        { discr: 'Acerola saquinho', pUnit: '5.00', medida: 'unid'},
        { discr: 'Abacaxi', pUnit: '4.00', medida: 'unid'},
        { discr: 'Abacate', pUnit: '7.50', medida: 'kg'},
        { discr: 'Caju', pUnit: '1.00', medida: 'unid'},
        { discr: 'Goiaba', pUnit: '5.00', medida: 'kg'},
        { discr: 'Melancia Grande', pUnit: '20.00', medida: 'unid'},
        { discr: 'Melancia Pequena', pUnit: '10.00', medida: 'unid'},
        { discr: 'Melancia baby s/semente', pUnit: '6.00', medida: 'unid'},
        { discr: 'Uva verde ', pUnit: '13.00', medida: 'kg'},
        { discr: 'Uva verde sem semente', pUnit: '15.00', medida: 'kg'},
        { discr: 'Uva preta Isabel (suco)', pUnit: '12.00', medida: 'kg'},
        { discr: 'Uva preta Vitória s/caroço', pUnit: '14.00', medida: 'kg'},
        { discr: 'Uva verde algodão doce', pUnit: '18.00', medida: 'bdj'},
        { discr: 'Uva rose melodia', pUnit: '15.00', medida: 'kg'},
        { discr: 'Maçã crocante', pUnit: '10.00', medida: 'kg'},
        { discr: 'Banana prata/pacovan', pUnit: '6.00', medida: 'unid'},
        { discr: 'Banana da terra', pUnit: '2.50', medida: 'unid'},
        { discr: 'Pinha', pUnit: '2.50', medida: 'unid'},
        { discr: 'Pêra 3 unid', pUnit: '5.00', medida: 'unid'},
        { discr: 'Pêra Portuguesa', pUnit: '15.00', medida: 'kg'},
        { discr: 'Mamão comum', pUnit: '3.00', medida: 'unid'},
        { discr: 'Mamão Havaí', pUnit: '4.00', medida: 'kg'},
        { discr: 'Kiwi verde', pUnit: '30.00', medida: 'kg'},
        { discr: 'Kiwi yellow gold', pUnit: '35.00', medida: 'kg'},
        { discr: 'Morango Premium', pUnit: '40.00', medida: 'cx'},
        { discr: 'Morango', pUnit: '10.00', medida: 'bdj'},
        { discr: 'Maçã verde', pUnit: '15.00', medida: 'kg'},
        { discr: 'Laranja pera', pUnit: '0.75', medida: 'unid'},
        { discr: 'Laranja pokan G', pUnit: '2.00', medida: 'unid'},
        { discr: 'Tangerina importada', pUnit: '23.00', medida: 'kg'},
        { discr: 'Melão amarelo', pUnit: '4.00', medida: 'kg'},
        { discr: 'Melão Gaia/Orange', pUnit: '4.00', medida: 'kg'},
        { discr: 'Maracujá', pUnit: '9.00', medida: 'kg'},
        { discr: 'Manga Tommy', pUnit: '5.00', medida: 'kg'},
        { discr: 'Manga Espada', pUnit: '4.00', medida: 'kg'},
        { discr: 'Manga Palmer sem fiapo', pUnit: '5.00', medida: 'kg'},
        { discr: 'Limão', pUnit: '0.40', medida: 'unid'},
        { discr: 'Lichia/rambutā', pUnit: '20.00', medida: 'bdj'},
        { discr: 'Ameixa fresca 3 unid', pUnit: '6.00', medida: 'bdj'},
        { discr: 'Coco verde', pUnit: '2.50', medida: 'unid'},
        { discr: 'Coco seco', pUnit: '4.00', medida: 'unid'},
        { discr: 'Coco ralado in natura', pUnit: '6.00', medida: 'unid'},
        { discr: 'Água de coco natural 1l', pUnit: '12.00', medida: 'unid'}
    ],
    'verduras': [
        { discr: 'Abobrinha', pUnit: '2.00', medida: 'unid'},
        { discr: 'Tomate', pUnit: '5.00', medida: 'kg'},
        { discr: 'Tomate cereja', pUnit: '6.00', medida: 'bdj'},
        { discr: 'Cebola branca', pUnit: '7.00', medida: 'kg'},
        { discr: 'Cebola roxa', pUnit: '7.00', medida: 'kg'},
        { discr: 'Berinjela', pUnit: '3.00', medida: 'kg'},
        { discr: 'Batatinha', pUnit: '8.00', medida: 'kg'},
        { discr: 'Cenoura', pUnit: '9.00', medida: 'kg'},
        { discr: 'Chuchu', pUnit: '1.50', medida: 'unid'},
        { discr: 'Acelga', pUnit: '6.00', medida: 'kg'},
        { discr: 'Beterraba', pUnit: '5.00', medida: 'kg'},
        { discr: 'Couve flor', pUnit: '10.00', medida: 'unid'},
        { discr: 'Brócolis', pUnit: '10.00', medida: 'unid'},
        { discr: 'Pepino comum', pUnit: '1.50', medida: 'unid'},
        { discr: 'Pepino japonês', pUnit: '2.00', medida: 'unid'},
        { discr: 'Pimentão', pUnit: '1.00', medida: 'unid'},
        { discr: 'Pimenta de cheiro 250g', pUnit: '4.00', medida: 'unid'},
        { discr: 'Jiló 250g', pUnit: '3.00', medida: '', medida: 'bdj'},
        { discr: 'Vagem 250g', pUnit: '3.00', medida: '', medida: 'bdj'},
        { discr: 'Quiabo', pUnit: '5.00', medida: 'kg'},
        { discr: 'Maxixe', pUnit: '7.00', medida: 'kg'},
        { discr: 'Repolho verde', pUnit: '6.00', medida: 'kg'},
        { discr: 'Repolho roxo', pUnit: '8.00', medida: 'kg'},
        { discr: 'Jirimum', pUnit: '4.00', medida: 'kg'},
        { discr: 'Batata doce', pUnit: '4.00', medida: 'kg'},
        { discr: 'Cará', pUnit: '8.00', medida: 'kg'},
        { discr: 'Inhame', pUnit: '10.00', medida: 'kg'},
        { discr: 'Macaxeira na casca', pUnit: '5.00', medida: 'kg'},
        { discr: 'Macaxeira descascada', pUnit: '6.00', medida: 'kg'},
        { discr: 'Feijão verde', pUnit: '12.00', medida: 'kg'},
        { discr: 'Fava verde', pUnit: '15.00', medida: 'kg'},
        { discr: 'Alho roxo (G)', pUnit: '2.50', medida: 'unid'},
        { discr: 'Alho descascado', pUnit: '25.00', medida: 'kg'},
        { discr: 'Goma pura (brejeira)', pUnit: '7.00', medida: 'kg'},
        { discr: 'Ovos 15und vermelhos', pUnit: '13.00', medida: 'cx'},
        { discr: 'Ovos 30und vermelhos', pUnit: '23.00', medida: 'cx'}
    ]
};