// adicione aqui os seus produtos fixos:
var items = [
    { discr: 'Abacate',       pUnit: '6.00', medida: 'kg'   },
    { discr: 'Abacaxi',       pUnit: '5.00', medida: 'unid' },
    { discr: 'Acelga',        pUnit: '7.00', medida: 'kg'   },
    { discr: 'Banana',        pUnit: '3.00', medida: 'palm' },
    { discr: 'Barbante',      pUnit: '12.0', medida: 'kg'   },
    { discr: 'Abobrinha',     pUnit: '4.00', medida: 'kg'   },
    { discr: 'Alecrim',       pUnit: '1.00', medida: 'unid' },
    { discr: 'Alface amer.',  pUnit: '1.50', medida: 'unid' },
    { discr: 'Alface cres.',  pUnit: '1.50', medida: 'unid' },
    { discr: 'Alface roxa',   pUnit: '1.50', medida: 'unid' },
    { discr: 'Alho roxo',     pUnit: '22.0', medida: 'kg'   },
    { discr: 'Alho-poró',     pUnit: '2.00', medida: 'unid' },
    { discr: 'Batata doce',   pUnit: '3.00', medida: 'kg'   },
    { discr: 'Batata ing.',   pUnit: '8.00', medida: 'kg'   },
    { discr: 'Berinjela',     pUnit: '4.00', medida: 'kg'   },
    { discr: 'Beterraba',     pUnit: '5.00', medida: 'kg'   },
    { discr: 'Brócolis',      pUnit: '8.00', medida: 'unid' },
    { discr: 'Cará',          pUnit: '7.00', medida: 'kg'   },
    { discr: 'Cebola bran.',  pUnit: '6.00', medida: 'kg'   },
    { discr: 'Cebola roxa',   pUnit: '6.00', medida: 'kg'   },
    { discr: 'Cebolinha',     pUnit: '3.00', medida: 'unid' },
    { discr: 'Cenoura',       pUnit: '9.00', medida: 'kg'   },
    { discr: 'Chuchu',        pUnit: '1.00', medida: 'unid' },
    { discr: 'Coentro',       pUnit: '1.00', medida: 'maço' },
    { discr: 'Couve-flor',    pUnit: '8.00', medida: 'unid' },
    { discr: 'Couve',         pUnit: '1.00', medida: 'unid' },
    { discr: 'Espinafre',     pUnit: '1.00', medida: 'unid' },
    { discr: 'Feijão verde',  pUnit: '14.0', medida: 'kg'   },
    { discr: 'Gengibre',      pUnit: '20.0', medida: 'kg'   },
    { discr: 'Goma',          pUnit: '5.00', medida: 'kg'   },
    { discr: 'Hortelã',       pUnit: '1.00', medida: 'unid' },
    { discr: 'Inhame',        pUnit: '7.00', medida: 'kg'   },
    { discr: 'Jerimum',       pUnit: '5.00', medida: 'kg'   },
    { discr: 'Jiló',          pUnit: '5.00', medida: 'kg'   },
    { discr: 'Laranja com.',  pUnit: '0.70', medida: 'unid' },
    { discr: 'Limão',         pUnit: '0.25', medida: 'unid' },
    { discr: 'Macaxeira',     pUnit: '5.00', medida: 'kg'   },
    { discr: 'Mamão formo.',  pUnit: '3.00', medida: 'kg'   },
    { discr: 'Mamão havaí.',  pUnit: '4.50', medida: 'kg'   },
    { discr: 'Manga Tommy',   pUnit: '5.00', medida: 'kg'   },
    { discr: 'Manjericão',    pUnit: '1.00', medida: 'unid' },
    { discr: 'Maracujá',      pUnit: '11.0', medida: 'kg'   },
    { discr: 'Maxixe',        pUnit: '5.00', medida: 'kg'   },
    { discr: 'Maçã fuji',     pUnit: '10.0', medida: 'kg'   },
    { discr: 'Maçã gala',     pUnit: '10.0', medida: 'kg'   },
    { discr: 'Pimenta che.',  pUnit: '10.0', medida: 'kg'   },
    { discr: 'Pepino japo.',  pUnit: '5.00', medida: 'kg'   },
    { discr: 'Pepino',        pUnit: '4.00', medida: 'kg'   },
    { discr: 'Pimentão',      pUnit: '0.70', medida: 'unid' },
    { discr: 'Quiabo ',       pUnit: '5.00', medida: 'kg'   },
    { discr: 'Repolho roxo',  pUnit: '7.00', medida: 'kg'   },
    { discr: 'Repolho ver.',  pUnit: '4.00', medida: 'kg'   },
    { discr: 'Rúcula',        pUnit: '1.00', medida: 'unid' },
    { discr: 'Salsa',         pUnit: '1.00', medida: 'unid' },
    { discr: 'Tempero nat.',  pUnit: '2.00', medida: 'kg'   },
    { discr: 'Tomate',        pUnit: '5.00', medida: 'kg'   },
    { discr: 'Uva Vitória',   pUnit: '14.0', medida: 'kg'   },
    { discr: 'Vagem',         pUnit: '7.00', medida: 'kg'   }
    ];
